# Generated by Django 4.2.7 on 2023-11-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('price', models.CharField(max_length=20)),
                ('contacts', models.JSONField(default=list)),
                ('hide', models.BooleanField(default=False)),
                ('shortlist', models.BooleanField(default=False)),
            ],
        ),
    ]
