# Generated by Django 4.2.7 on 2023-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_alter_designers_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designers',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
